### ISSUE TITLE
US_#1_As a user, I want to be able to make a request for a delivery

### ISSUE THREAD

**Issue by Julia-Trinh** [cristina-trofimov/WLW_soen343#2]
## Tasks:
- [x] Design UI for the form for making a request for delivery
- [x] Implement backend for the creation of a delivery object
- [x] Implement quotation logic (same as in US_#2)

**Comment by Julia-Trinh** [comment]
Done, but will need a 'My Orders' page specific to the user
