### ISSUE TITLE
US_#3_As a user, I want to be able to leave a review once my package has been delivered

### ISSUE THREAD

**Issue by Julia-Trinh** [cristina-trofimov/WLW_soen343#4]
## Tasks:
- [x] Design UI for the customers to browse their deliveries ("My Deliveries" page)
- [ ] Design UI for a review page
- [ ] Add backend for a review
