### ISSUE TITLE
US_#4_As a user, I want to be able to track a package that is being delivered without being logged on

### ISSUE THREAD

**Issue by Julia-Trinh** [cristina-trofimov/WLW_soen343#5]
## Task:
- [x] Design UI for the tracking page
- [x] Implement backend to update the delivery status
- [x] Implement backend to search for a delivery with a tracking number
